Application\Entity\Track:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    tilte:
      type: string
      length: 255
      nullable: true
    artist:
      type: string
      length: 255
      nullable: true
    duration:
      type: string
      length: 255
      nullable: true
